const sortModels = (models: string[]) => {
  const defaultItem = models.find(m => m.startsWith('Default'));
  const others = models.filter(m => !m.startsWith('Default')).sort((a, b) => a.localeCompare(b));
  return defaultItem ? [defaultItem, ...others] : others;
};

export const TARGET_IMAGE_AI_MODELS = sortModels([
  'FLUX.2 [pro]',
  'FLUX.2 [dev]',
  'FLUX.2 [klein]',
  'FLUX.1.1 [pro]',
  'FLUX.1 [dev/schnell]',
  'Midjourney v8.1',
  'Midjourney v8 Alpha',
  'Midjourney v7',
  'Midjourney v6.1',
  'GPT Image 2 (OpenAI)',
  'GPT-5 Image (DALL-E 4)',
  'GPT-4o Image (DALL-E 3)',
  'Google Imagen 4 (Nano Banana Pro)',
  'Google Nano Banana 2 (Gemini 3.1 Flash)',
  'Google Imagen 3',
  'Stable Diffusion 4.0 Large',
  'Stable Diffusion 3.5 Large',
  'Ideogram 3.0',
  'Ideogram 2.0',
  'Recraft V4',
  'Recraft V3',
  'HiDream-O1-Image-1.5',
  'Seedream 5.0',
  'Seedream 4.0',
  'Playground v3',
  'PONY Diffusion XL (v6)',
  'Illustrious XL',
  'Stable Diffusion XL',
  'Chroma v1',
  'Grok-3 Image (xAI)',
  'Grok-2 Image (xAI)',
  'HunYuan DiT v1.2',
  'Janus-V2 (DeepSeek)',
  'Janus-Pro (DeepSeek)',
  'Lumina-T2I',
  'Lumina-Image 2.0',
  'WAN Image (T2I)',
  'Z-Image',
  'Qwen-Image',
  'Adobe Firefly 4',
  'Default (General Purpose)',
]);

export const TARGET_VIDEO_AI_MODELS = sortModels([
  'LTX-2',
  'LTX-3 (Narrative Video)',
  'Google Veo 3.1',
  'Google Veo 3.1 Lite',
  'Google Veo 3',
  'Google Veo 2',
  'Kling 3.0 Pro / Turbo / Omni',
  'Kling 2.5 Turbo',
  'Kling 2.0 Pro',
  'Kling 1.5 Pro',
  'Runway Gen-4.5',
  'Runway Gen-4 Alpha',
  'Runway Gen-3 Alpha Turbo',
  'Luma Dream Machine (Ray 3.14)',
  'Luma Ray (v3)',
  'Luma Ray (v2)',
  'Sora 2 (OpenAI) — sunset Sep 2026',
  'Sora (OpenAI)',
  'MiniMax Hailuo 2.3',
  'Hailuo 02',
  'Hailuo MiniMax-V2',
  'Seedance 2.0 (ByteDance)',
  'Seedance 1.0 Pro',
  'HappyHorse 1.1 (Alibaba)',
  'SkyReels V4 (Skywork AI)',
  'WAN 2.7 (Open Weights)',
  'WAN 2.5',
  'WAN Video v2 (T2V)',
  'Pika Art v3.0',
  'Pika Art v2.1',
  'HunYuan Video v2',
  'Vidu 2.0',
  'HiDream (Excellence)',
  'CogVideoX-5B',
  'Higgsfield (Alaya)',
  'Mochi 1 (Genmo)',
  'PixVerse V5',
  'Default (General Video)',
]);

export const TARGET_AUDIO_AI_MODELS = sortModels([
  'ElevenLabs v3 (TTS)',
  'ElevenLabs Music v2',
  'ElevenLabs Music',
  'MMAudio v2 (Sound FX)',
  'Vibe Voice',
  'Suno v5.5 (Music)',
  'Suno v5 (Music)',
  'Suno v4 (Music)',
  'Udio 1.5 (48kHz)',
  'Udio v2 (High-Fidelity)',
  'Stable Audio 3.0 (Open Weight)',
  'AudioLDM 2',
  'AudioBox (Meta)',
  'OpenAI Voice Engine',
  'Bark (Suno)',
  'MiniMax Music 2.5',
  'MiniMax Speech-02',
  'Mureka (Lyrics-First)',
  'Lyria 3 (Google)',
  'Lyria 2 (Google)',
  'ACE-Step 1.5 (Open)',
  'ACE-Step (Music)',
  'Kokoro TTS',
  'Qwen3-TTS',
  'Fish Audio S1',
  'Default (General Audio)',
]);

export const AVAILABLE_LLM_MODELS = [
    { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash (Fastest)' },
    { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro (Smarts)' },
    { id: 'gemini-3.1-flash-lite-preview', name: 'Gemini 3.1 Flash Lite' },
    { id: 'gemini-3.1-flash-preview', name: 'Gemini 3.1 Flash' }
];