export const PROMPT_DETAIL_LEVELS = {
  SHORT: 'Short',
  MEDIUM: 'Medium',
  LONG: 'Long',
};

// --- Standard Aspect Ratios ---
export const GENERAL_ASPECT_RATIOS = ["1:1", "3:4", "4:3", "9:16", "16:9"];

// --- Midjourney Specific Modifiers ---
export const MIDJOURNEY_VERSIONS = ["7", "6.1", "6", "5.2", "5.1", "5", "4"];
export const MIDJOURNEY_NIJI_VERSIONS = ["6", "5", "4"];
export const MIDJOURNEY_ASPECT_RATIOS = ["1:1", "2:3", "3:2", "4:5", "5:4", "9:16", "16:9"];

// --- Audio Specific Modifiers ---
export const AUDIO_TYPES = [
    'Dialogue / Speech',
    'Narration / Voiceover',
    'Ambient Background',
    'Sound Effects (SFX)',
    'Musical Composition',
    'Foley Recording',
    'Binaural / 3D Audio',
    'Podcast Segment',
    'ASMR',
    'Audiobook',
    'Meditation / Sleep',
    'Jingle / Sonic Logo',
    'Trailer Sound Design',
    'Game SFX',
    'Loopable Ambience',
    'Radio Drama'
];

export const VOICE_GENDERS = ['Masculine', 'Feminine', 'Androgynous', 'Child', 'Elderly'];

export const VOICE_TONES = [
    'Deep / Bass', 'Smooth / Silk', 'Raspy / Gravelly', 'Energetic / Bright',
    'Monotone / Robotic', 'Whispering / Soft', 'Commanding / Authoritative',
    'Sarcastic / Playful', 'Melancholic / Sad', 'Terrified / Shaky',
    'Warm Narrator', 'Hushed Documentary', 'Hype Announcer',
    'Deadpan', 'Soothing ASMR', 'Gravelly Noir',
    'Corporate Explainer', 'Storyteller Grandparent',
    'Cultivational / Calm', 'Gritty Streetwise'
];

export const AUDIO_ENVIRONMENTS = [
    'Studio / Dry', 'Large Cathedral Hall', 'Tiled Bathroom', 'Outdoor Forest',
    'Crowded City Street', 'Under water', 'Empty Warehouse', 'Small Cozy Room',
    'Telephone / Radio Filter', 'Space Vacuum',
    'Concert Arena', 'Parking Garage', 'Padded Booth',
    'Cave System', 'Open Ocean', 'Night Forest',
    'Spaceship Interior Hum', 'Vinyl Room Tone'
];

export const AUDIO_MOODS = [
    'Cinematic', 'Suspenseful', 'Hopeful', 'Dark & Gritty',
    'Upbeat & Fun', 'Ethereal / Dreamy', 'Aggressive', 'Calm / Zen',
    'Triumphant', 'Ominous Drone', 'Bittersweet', 'Nostalgic',
    'Playful Whimsy', 'Meditative', 'Urgent Breaking-News', 'Romantic',
    'Melancholic', 'Mysterious'
];

// --- Z-Image Specific Styles ---
export const Z_IMAGE_STYLES = [
    'Lo-fi Mobile Photo',
    'Casual Mobile Photo',
    'Vintage Candid Photo',
    'Classic Film Photo',
    'Analog Photo',
    'Vintage Introspection',
    'Wide Angle / Peephole',
    'Low-Poly Render',
    'Comic',
    'Vintage Comic',
    'Anime',
    'Oil Painting',
    'Minimalist Sketchwash',
    'Retro Pixel Art',
    'Editorial Flash',
    'CCTV Still',
    'Risograph Print',
    'Gouache Illustration'
];

export interface DescriptiveOption {
  name: string;
  description: string;
}

// --- Digital Trends & Social Aesthetics ---
export const DIGITAL_AESTHETICS: DescriptiveOption[] = [
    { name: 'Wes Anderson Trend', description: 'Symmetry, Pastel, Static Composition' },
    { name: 'Coquette Aesthetic', description: 'Pink, Ribbons, Vintage Soft, Feminine' },
    { name: 'Dark Academia', description: 'Tweed, Libraries, Moody Lighting, Intellectual' },
    { name: 'Cottagecore', description: 'Rural, Floral, Nostalgic, Pastoral' },
    { name: 'Barbiecore', description: 'Hot Pink, High-Gloss, Plastic, Maximalist' },
    { name: 'Y2K Aesthetic', description: 'Cyber, Metallic, Futuristic 2000s, Iridescent' },
    { name: '90s Grunge', description: 'Lo-fi, Gritty, Oversized, Grainy, Counter-culture' },
    { name: 'Indie Sleaze', description: 'Flash Photography, Messy, 2010s Retro, Party' },
    { name: 'E-Girl / E-Boy', description: 'Neon, High Contrast, Digital, Alternative' },
    { name: 'Vibe-core', description: 'Abstract, Ethereal, Lighting-focused, Atmospheric' },
    { name: 'Clean Girl Aesthetic', description: 'Minimalist, Beige, De-puffed, Polished' },
    { name: 'Soft Girl', description: 'Pastel, Ethereal, Gentle Lighting, Cute' },
    { name: 'Baddie Aesthetic', description: 'Sharp, High-Glamour, Urban, Fierce' },
    { name: 'Scandi Minimalist', description: 'Clean Lines, Natural Wood, Bright, Functional' },
    { name: 'Moody Tones', description: 'Crushed Blacks, Deep Greens, Melancholic, Somber' },
    { name: 'That Girl', description: 'Wellness, Productivity, Bright, Organized, Aesthetic' },
    { name: 'Disposable Camera', description: 'Flash, Red-eye, High Grain, Candid' },
    { name: 'Paparazzi Candid', description: 'Motion Blur, Flash, Staged-Realism, Hectic' },
    { name: 'Old Money / Quiet Luxury', description: 'Classic, Rich Textures, Understated, Timeless' },
    { name: 'Gorpcore', description: 'Outdoor, Tech-utility, Tactical, Functional' },
    { name: 'Techwear', description: 'Cyberpunk Fashion, Straps, All-Black, Futuristic' },
    { name: 'Streetwear High-Fashion', description: 'Graffiti, Bold Logos, Urban, Designer' },
    { name: 'Balletcore', description: 'Tulle, Silk, Graceful, Soft Lighting, Classical' },
    { name: 'Stealth Wealth', description: 'Understated, High-Quality Fabric, Anonymous Luxury' },
    { name: 'Cyber-Street', description: 'Neon-accented, Urban Futuristic, Night-life' },
    { name: 'Dreamcore', description: 'Uncanny, Surreal, Liminal Space, Nostalgic' },
    { name: 'Weirdcore', description: 'Low-res, Glitchy, Nonsensical, Unsettling' },
    { name: 'Vaporwave', description: '80s Cyan/Magenta, Retro-Digital, Surreal' },
    { name: 'Cyber-Y2K', description: 'Glitch, Chrome, Fisheye Lens, Tech-Retro' },
    { name: 'Lo-fi Hip Hop', description: 'Anime Style, Warm, Cozy, Chilled' },
    { name: 'Backrooms Aesthetic', description: 'Yellowed, Fluorescent, Liminal, Eerie' },
    { name: 'Frutiger Aero', description: 'Glossy, Water, Bubbles, 2000s Tech, Optimistic' },
    { name: 'Mob Wife', description: 'Leopard, Fur, Statement Gold Jewelry, Dark Glamour' },
    { name: 'Tomato Girl', description: 'Red-Toned, Mediterranean, Warm Lighting, Casual Chic' },
    { name: 'Office Siren', description: 'Tailored, Corporate Corsetry, Sleek, Power Dressing' },
    { name: 'Eclectic Grandpa', description: 'Layered Patterns, Wool Textures, Vintage Finds' },
    { name: 'Coastal Grandmother', description: 'Linen, Stripes, Neutral Palette, Beachside Serenity' },
    { name: 'Solarpunk', description: 'Bright Green, Solar Tech, Optimistic Eco-Future' },
    { name: 'Fairycore', description: 'Magical, Translucent Wings, Woodland, Soft Pastel' },
    { name: 'Gothcore', description: 'Dark Victorian, Lace, Corsets, Subcultural Dark' },
    { name: 'Kidcore', description: 'Primary Colors, 90s Toys, Hyper-Saturated, Playful' },
    { name: 'Blokecore', description: 'Retro Football Kits, Terrace Culture, 90s Sportswear' },
    { name: 'Acubi', description: 'Minimalist Avant-Garde, Structural Silhouettes, Deconstructed' },
    { name: 'Nostalgiacore', description: 'Nostalgia-Induced, Warm Memory Haze, Late 90s/Early 00s' },
    { name: 'Corporate Memphis', description: 'Flat, Exaggerated Limbs, 2010s Tech Illustration Style' },
    { name: 'Neo-Brutalist Web', description: 'Raw HTML, Monochrome, Functional, Anti-Design' },
    { name: 'Cyber Fairy Grunge', description: 'Iridescent, Ripped Mesh, Digital Decay, Pastel Goth' },
    { name: 'Whimsigoth', description: 'Mystical, Velvet, Celestial Motifs, Moody Jewel Tones' },
    { name: 'Coquette Academia', description: 'Plaid, Bow Ties, Glasses, Studious Yet Feminine' },
    { name: 'Brat Green', description: 'Lime Green, Y2K Revival, Messy Attitude, Slimy Aesthetic' },
    { name: 'Seapunk', description: 'Aquatic, 90s Internet, Cyan, Shell Motifs, Neon' },
    { name: 'Normcore', description: 'Unassuming, Anti-Fashion, Practical, Generic Minimal' },
    { name: 'Poetcore', description: 'Literary Romance, Inky Neutrals, Soft Layers, Handwritten Details' },
    { name: 'Aliencore', description: 'Bionic Shapes, Iridescent Skin, Otherworldly Gloss, Acid Tones' },
    { name: 'Circuscore', description: 'Theatrical Stripes, Carnival Color, Playful Drama, Vintage Spectacle' },
    { name: '80s Maximalism', description: 'Power Shoulders, Lacquered Color, High Drama, Opulent Excess' },
    { name: 'Sportif', description: 'Technical Sportswear, Refined Tailoring, Performance Details, Clean Energy' },
    { name: 'Modern Heirloom', description: 'Vintage Craft, Rich Patina, Sentimental Objects, Collected Layers' },
    { name: 'Tactile Minimalism', description: 'Quiet Forms, Handmade Texture, Soft Neutrals, Material Warmth' },
    { name: 'Neo-Medieval', description: 'Heraldic Motifs, Chainmail Texture, Illuminated Color, Future Fantasy' },
    { name: 'Analog Craft Revival', description: 'Visible Paper Grain, Hand-Drawn Marks, Imperfect Print, Human Touch' },
    { name: 'Soft Industrial', description: 'Brushed Metal, Translucent Plastic, Rounded Utility, Gentle Light' },
    { name: 'Night Garden', description: 'Botanical Darkness, Wet Foliage, Jewel Tones, Nocturnal Romance' },
    { name: 'Desert Modern', description: 'Sun-Baked Earth Tones, Sculptural Forms, Sparse Luxury, Long Shadows' },
    { name: 'Hyperlocal Nostalgia', description: 'Everyday Landmarks, Community Ephemera, Familiar Texture, Memory Haze' }
];

// --- Movie Aesthetics / Cinematic Looks ---
export const AESTHETIC_LOOKS: DescriptiveOption[] = [
    { name: 'Wes Anderson', description: 'Symmetrical, Pastel, Whimsical, Centered' },
    { name: 'Christopher Nolan', description: 'High Contrast, Cold Blue, Crisp, Epic' },
    { name: 'Denis Villeneuve', description: 'Brutalist, Scale, Atmospheric Haze, Minimalist' },
    { name: 'Wong Kar-wai', description: 'Saturated, Motion Blur, Melancholic, Neon' },
    { name: 'Quentin Tarantino', description: 'Gritty 70s, Saturated, Retro, Violent' },
    { name: 'Stanley Kubrick', description: 'Clinical, One-Point Perspective, Precise' },
    { name: 'Tim Burton', description: 'Gothic, Dark Whimsy, German Expressionism' },
    { name: 'Michael Bay', description: 'High Saturation, Anamorphic Flare, Dynamic' },
    { name: 'Zack Snyder', description: 'Desaturated, High Contrast, Crushed Blacks' },
    { name: 'Guillermo del Toro', description: 'Fairy Tale, Amber/Teal, Organic, Macabre' },
    { name: 'David Lynch', description: 'Surreal, High Contrast Shadows, Dreamlike' },
    { name: 'Akira Kurosawa', description: 'High Contrast B&W, Epic Composition, Dynamic' },
    { name: 'Blade Runner', description: 'Cyberpunk, Neon Noir, Rainy, Melancholic' },
    { name: 'Mad Max', description: 'Orange/Teal, Gritty, Post-Apocalyptic, Kinetic' },
    { name: 'The Matrix', description: 'Green-Tinted, Urban Decay, Digital, Sharp' },
    { name: 'Sin City', description: 'High Contrast B&W, Selective Red, Noir' },
    { name: 'Studio Ghibli', description: 'Lush Nature, Painterly, Nostalgic, Whimsical' },
    { name: 'Film Noir', description: 'Chiaroscuro, Smokey, Dramatic Shadows, Noir' },
    { name: 'Barbiecore', description: 'Hot Pink, High-Key, Plasticity, Vibrant' },
    { name: 'Dune Aesthetic', description: 'Epic Scale, Minimalist, Sand-swept, Cinematic' },
    { name: 'Arcane Style', description: 'Painterly 3D, Stylized Lighting, Saturated' },
    { name: 'Succession', description: 'Corporate Realism, Handheld, Quiet Luxury' },
    { name: 'Euphoria Look', description: 'Neon Purple, Glitter, Dreamy Haze, Saturated' },
    { name: 'Spaghetti Western', description: 'Gritty, Extreme Close-ups, Heat Haze' },
    { name: 'Folk Horror', description: 'Overexposed, Ritualistic, Midsommar Style' },
    { name: 'Giallo', description: 'Primary Colors, Stylized Horror, 70s Italian' },
    { name: 'Slasher Horror', description: 'Low-key, Gritty Grain, Suspenseful, Dark' },
    { name: 'Found Footage', description: 'VHS Glitch, Low-res, Handheld, Raw' },
    { name: 'CCTV / Security Cam', description: 'Grainy, High-Angle, Wide-Angle, Raw' },
    { name: 'Bridgerton', description: 'Period Drama, Saturated Floral, Soft Glow' },
    { name: 'Avatar', description: 'Bioluminescent, Vibrant Cyan, Exotic Flora' },
    { name: 'Interstellar', description: 'Cosmic Realism, NASA Aesthetic, Atmospheric' },
    { name: 'Cyberpunk 2077', description: 'High-Tech Night, Glitchy Neon, Urban' },
    { name: 'Disney/Pixar 3D', description: 'High Polish, Expressive, Clean, Soft' },
    { name: 'Spider-Verse', description: 'Comic-Book Halftone, Multiversal, Stylized' },
    { name: 'A24 Horror', description: 'Minimalist, Eerie Naturalism, Atmospheric' },
    { name: 'Vaporwave', description: '80s Neon, Surreal Pink/Cyan, Retro-Future' },
    { name: 'Dreamcore / Weirdcore', description: 'Uncanny, Nostalgic, Surreal, Liminal' },
    { name: '90s Sitcom', description: 'Low Contrast, Soft Lighting, Set-Look, Flat' },
    { name: 'Technicolor Classic', description: 'Vibrant 1950s Look, High Saturation' },
    { name: 'War Cinema', description: 'Gritty, Desaturated, Saving Private Ryan Style' },
    { name: 'Space Opera', description: 'Epic, Lived-in Future, Star Wars Look' },
    { name: 'Oppenheimer', description: 'High Contrast B&W, IMAX, Intense Close-Ups, Period' },
    { name: 'Blade Runner 2049', description: 'Expansive, Neon-Washed, Holographic, Cold' },
    { name: 'Poor Things', description: 'Fisheye, Steampunk Color, Desaturated Victorian, Quirky' },
    { name: 'Saltburn', description: 'Sun-Drenched, 2000s Indie Grit, Rich Tapestry, Tension' },
    { name: 'Severance', description: 'Sterile Corporate, Green-Gray Tint, Flat Lighting' },
    { name: 'Andor', description: 'Gritty Rebel, Industrial, Practical Sets, Grounded Sci-Fi' },
    { name: 'The Bear', description: 'Handheld, Harsh Fluorescent, Kitchen Heat, Raw' },
    { name: 'Past Lives', description: 'Soft Natural, Melancholic Warmth, Intimate Framing' },
    { name: 'Everything Everywhere', description: 'Chaotic Multiverse, Rapid Cuts, Maximalist' },
    { name: 'Furiosa', description: 'Orange Dust, Desolate Horizon, Kinetic Fury, Epic' },
    { name: 'Fallout', description: 'Retro-Future, Irradiated Green, Vault-Tec Sterile' },
    { name: 'Wednesday', description: 'Gothic School, Monochrome Wardrobe, Moody Shadows' },
    { name: 'Dune Part Two', description: 'Monochrome Arena, Black Sun, Epic Scale, Harsh' },
    { name: 'The Batman', description: 'Red Saturated Noir, Rain-Slicked, Gritty Gotham' },
    { name: 'Sinners', description: 'Period Gothic South, Blood Red, Spiritual Horror' },
    { name: 'K-Drama Soft Look', description: 'Soft Diffuse, Warm Flush, Flattering Skin Tone, Romantic' },
    { name: 'Midsommar', description: 'Overexposed Flower, Bright Pastel, Daylight Horror' },
    { name: 'Parasite', description: 'Class Divide Framing, Rain-Soaked, Naturalistic' },
    { name: 'Tactile Editorial', description: 'Paper Grain, Tactile Materials, Imperfect Detail, Art-Directed Layout' },
    { name: 'Warm Minimalism', description: 'Soft Neutrals, Natural Materials, Generous Space, Quiet Refinement' },
    { name: 'Neo-Medieval Fantasy', description: 'Illuminated Manuscript Color, Ornate Metalwork, Heraldic Drama, Future Myth' },
    { name: 'Botanical Surrealism', description: 'Overscaled Flora, Dream Logic, Saturated Nature, Sculptural Forms' },
    { name: 'Sculptural Softness', description: 'Inflated Forms, Rounded Silhouettes, Diffused Light, Gentle Color' },
    { name: 'Artisanal Collage', description: 'Cut Paper, Scanned Texture, Layered Ephemera, Handmade Composition' },
    { name: 'Contemporary Gothic', description: 'Black Lacquer, Romantic Shadows, Deep Crimson, Modern Silhouettes' },
    { name: 'High-Gloss Camp', description: 'Exaggerated Glamour, Lacquered Surfaces, Bold Color, Playful Excess' },
    { name: 'Techno-Organic', description: 'Biomorphic Technology, Translucent Surfaces, Living Systems, Clean Futurism' },
    { name: 'Documentary Intimacy', description: 'Natural Light, Close Observation, Honest Texture, Unposed Moments' },
    { name: 'Post-Digital Nostalgia', description: 'Early-Web Artifacts, Soft Compression, Retro Interface, Sentimental Tech' },
    { name: 'Future Folk', description: 'Traditional Craft Motifs, Experimental Materials, Mythic Color, Handmade Future' }
];

// --- Refiner Dropdown Options ---
export const COMPOSITION_OPTIONS = [
    'Rule of Thirds', 'Golden Ratio', 'Leading Lines', 'Symmetry', 'Asymmetrical Balance',
    'Frame within a Frame', 'Vanishing Point', 'Centered Composition', 'Diagonal Composition',
    'Negative Space', 'Radial Composition', 'Triangular Composition', 'Dynamic Symmetry',
    'Layered Depth', 'Foreground Framing', 'Isolation', 'Pattern Interruption',
    'Figure-to-Ground', 'Dead Center Minimal', 'Off-Center Tension', 'Spiral Composition',
    'S-Curve', 'L-Shape', 'Cross Composition', 'Quadrant Grid', 'Juxtaposition'
];

export const CAMERA_ANGLES = [
    'Eye Level Shot',
    'High Angle Shot',
    'Low Angle Shot',
    'Bird\'s Eye View',
    'Worm\'s Eye View',
    'Dutch Angle (Canted)',
    'Over-the-Shoulder Shot',
    'POV (Point of View)',
    'Top-Down Shot',
    'Under-View Shot',
    'Hip Level Shot',
    'Knee Level Shot',
    'Ground Level Shot',
    'Shoulder Level Shot',
    'Extreme High Angle',
    'Extreme Low Angle',
    'Aerial Oblique',
    'Drone Top-Down 45°',
    'Mirror Reflection Angle',
    'Through-Object POV',
    'Security-Camera Corner',
    'Overhead Flat Lay'
];

export const CAMERA_PROXIMITY = [
    'Extreme Close-Up',
    'Close-Up',
    'Medium Close-Up',
    'Medium Shot',
    'Medium Long Shot',
    'Long Shot',
    'Full Shot',
    'Extreme Long Shot',
    'Establishing Shot',
    'Macro Shot',
    'Microscopic Shot',
    'Wide Shot',
    'Very Wide Shot',
    'Zoomed In',
    'Zoomed Out',
    'Telephoto Zoom',
    'Super Wide Angle',
    'Detail Shot',
    'Two-Shot',
    'Crowd Scale',
    'Aerial Establishing'
];

export const CAMERA_SETTINGS = [
    'Fast Shutter Speed',
    'Slow Shutter Speed',
    'Motion Blur',
    'Deep Depth of Field',
    'Shallow Depth of Field',
    'Bokeh',
    'Sharp Focus',
    'Soft Focus',
    'Out of Focus',
    'Lens Flare',
    'Chromatic Aberration',
    'High ISO Grain',
    'Long Exposure',
    'Double Exposure',
    'Time-lapse',
    'High Dynamic Range (HDR)',
    'Vignetting',
    'Motion Trails',
    'Light Painting',
    'High Contrast',
    'Low Contrast',
    'High Saturation',
    'Desaturated',
    'Overexposed',
    'Underexposed',
    'f/0.95 Razor DOF',
    'Focus Stacking',
    'ND Long Exposure',
    'Intentional Camera Movement (ICM)',
    'Zone Focusing',
    'Push Processing',
    'Halation Bloom',
    'Exposure Bracketing',
    'Lens Baby Effect',
    'Focal Length Blending'
];

export const CAMERA_EFFECTS = [
    'Abstract Effect',
    'Bokeh Blur',
    'Cross-processing',
    'Cyanotype Toning',
    'Double Exposure',
    'Edge-softening',
    'Fisheye Distortion',
    'Film Grain',
    'High-key Lighting',
    'Infrared Look',
    'Kaleidoscope Pattern',
    'Lens Flare Sparkle',
    'Motion Blur Streak',
    'Orton Effect Glow',
    'Panning Blur',
    'Retro Vintage Look',
    'Starburst Effect',
    'Tilt-shift Miniature',
    'Ultraviolet Glow',
    'Vignetting Shading',
    'Wide-angle Stretch',
    'X-ray Vision Look',
    'Zoom Burst Blur',
    'Prism Fractal',
    'Freelensing',
    'Lens Whacking',
    'Anamorphic Squeeze Artifacts',
    'CCD Sensor Bloom',
    'Datamosh Smear',
    'Scanline CRT',
    'Split-Diopter Effect',
    'Lensbaby Selective Focus'
];

export const SPECIALTY_LENS_EFFECTS: DescriptiveOption[] = [
    { name: 'Helios 44-2 Swirly Bokeh', description: 'Vintage Soviet lens known for a distinct circular "swirling" background blur.' },
    { name: 'Petzval Spiral Bokeh', description: 'Classical 19th-century look with sharp centers and extreme spiral bokeh.' },
    { name: 'Meyer Optik Trioplan Soap Bubble Bokeh', description: 'Famous for "soap bubble" bokeh, where highlights have sharp, thin edges.' },
    { name: 'Anamorphic Oval Bokeh & Blue Streak', description: 'Cinematic widescreen look with oval bokeh and horizontal blue light flares.' },
    { name: 'Leica Noctilux Soft Focus Glow', description: 'Creamy, dreamlike "glow" with extremely shallow depth of field.' },
    { name: 'Canon 50mm f/0.95 Dream Lens Bloom', description: 'The "Dream Lens" known for massive light bloom and ethereal soft focus.' },
    { name: 'Minolta STF Smooth Trans Focus', description: 'Smooth Trans Focus for perfectly creamy, distraction-free backgrounds.' },
    { name: 'Lensbaby Sweet Spot Selective Blur', description: 'Selectively sharp center with dramatic, smeared blur towards edges.' },
    { name: 'Industar-61 Star-shaped Bokeh', description: 'Soviet macro lens known for producing unique star-shaped bokeh highlights.' },
    { name: 'Zenitar 50mm f/1.7 Gritty Sharpness', description: 'Gritty, vintage sharpness with a specific micro-contrast character.' },
    { name: 'Jupiter-9 Silky Portrait Rendering', description: 'Legendary portrait lens with a silky, painting-like rendering of skin.' },
    { name: 'Takumar Flare & Warmth', description: 'Vintage warmth and beautiful orange/gold multi-layered lens flares.' },
    { name: 'Cine-Nikkor Retro Vignetting', description: 'Retro cinema lens look with heavy vignetting and soft edge falloff.' },
    { name: 'Wollensak Raptar Soft Rendering', description: 'Mid-century soft-rendering lens used for classic glamor portraits.' },
    { name: 'Aerochrome Lens Filter Aesthetic', description: 'Mimics infrared film, turning greens into vibrant pinks and reds.' },
    { name: 'Infrared Wood Effect Optics', description: 'Captures heat signatures, making foliage appear snowy white and skies black.' },
    { name: 'Carl Zeiss Jena Biotar Swirl', description: 'Classic double-Gauss rendering with a sharp center and energetic swirled edge bokeh.' },
    { name: 'Carl Zeiss Jena Pancolar 3D Pop', description: 'Strong micro-contrast and subject separation with a crisp, dimensional vintage look.' },
    { name: 'Carl Zeiss Jena Flektogon Close-Focus Field Curve', description: 'Dramatic close focus with curved focus falloff and richly textured wide-angle detail.' },
    { name: 'Meyer-Optik Primoplan Soft Glow', description: 'Gentle spherical-aberration glow with a painterly, romantic wide-open portrait look.' },
    { name: 'Meyer-Optik Orestor 15-Blade Bokeh', description: 'Long-aperture-blade design that keeps defocused highlights round and smooth when stopped down.' },
    { name: 'Dallmeyer 3B Radial Blur', description: 'Sharp central subject surrounded by a dramatic radial whirl and soft falloff.' },
    { name: 'Canon FD SSC Cinematic Flare', description: 'Warm color, lowered contrast, and expressive sun flare for an unmistakably analog frame.' },
    { name: 'Canon FL Dreamy Low Contrast', description: 'Earlier manual Canon rendering with hazy highlights, soft contrast, and flare-prone character.' },
    { name: 'Minolta Rokkor Velvet Glow', description: 'Warm color transitions, smooth skin rendering, and a subtle wide-open glow.' },
    { name: 'Olympus Zuiko Compact Flare', description: 'Small vintage optic character with gentle veiling flare, rich color, and soft edge falloff.' },
    { name: 'Nikkor AI-S Classic 3D Separation', description: 'Crisp manual-focus contrast, natural color, and clean subject-to-background separation.' },
    { name: 'Konica Hexanon Amber Rendering', description: 'Warm amber-biased color, fine detail, and a restrained analog glow.' },
    { name: 'Contax Zeiss Planar Micro-Contrast', description: 'High local contrast with rich tonal separation and refined, dimensional focus transitions.' },
    { name: 'Leica Summar Uncoated Flare', description: 'Pre-war uncoated softness with pronounced veiling flare and luminous haloed highlights.' },
    { name: 'Jupiter-8 Sonnar Glow', description: 'Classic Sonnar softness with gentle highlight bloom and a compact rangefinder feel.' },
    { name: 'Mir-1 Wide-Angle Sunstar', description: 'Vintage Soviet wide angle with pronounced sunstars, flare, and bold edge character.' },
    { name: 'Tair-11A 20-Blade Portrait Bokeh', description: 'Twenty-blade aperture produces exceptionally round, smooth background highlights.' },
    { name: 'Pentacon 50mm Rainbow Bokeh', description: 'Playful soap-bubble highlights with colorful flare and a lively M42 vintage character.' },
    { name: 'Kodak Aero Ektar Atmospheric Bloom', description: 'Ultra-fast aerial optic look with shallow focus, gentle bloom, and cinematic softness.' },
    { name: 'Lomo OKC Cinema Lens Character', description: 'Soviet cinema-glass texture with soft corners, organic flare, and lower contrast.' }
];

export const FILM_TYPES = [
    'Black and White',
    'Monochromatic',
    'Polaroid',
    'Instax',
    'Kodachrome',
    'Ektachrome',
    'Fujifilm Velvia',
    'Agfacolor',
    'Technicolor',
    'Sepia',
    'Cyanotype',
    'Daguerreotype',
    'Orthochromatic',
    'Panchromatic',
    'Infrared Film',
    '35mm Film',
    '70mm IMAX',
    'Super 8',
    '16mm',
    'Grainy Film',
    'Damaged Film Stock',
    'Expired Film',
    'Cross Processed',
    'Bleach Bypass',
    'Autochrome',
    'Calotype',
    'Kodak Vision3 Motion Picture',
    'Wet Plate Collodion',
    'Tintype',
    'Large Format 8x10',
    'Half-Frame',
    'Redscale',
    'Lomochrome Purple',
    'Aerochrome'
];

export const LIGHTING_OPTIONS = [
    'Cinematic Lighting', 'Volumetric Lighting', 'Soft Light', 'Hard Light', 'Rim Lighting',
    'Backlighting', 'Studio Lighting', 'Golden Hour', 'Blue Hour', 'Neon Lighting',
    'Chiaroscuro', 'Ambient Occlusion', 'Global Illumination', 'Crepuscular Rays',
    'Rembrandt Lighting', 'Split Lighting', 'Butterfly Lighting', 'Clamshell Lighting',
    'Practicals Only', 'Candlelight', 'Moonlight', 'Harsh Direct Flash',
    'Gobo Patterns', 'Caustics', 'North-Window Light', 'Tenebrism',
    'UV / Blacklight', 'Sodium Vapor Light', 'Tungsten Practicals', 'Ring Light',
    'Light Through Blinds', 'Dappled Forest Light', 'Underwater God Rays',
    'Bioluminescent Glow', 'Overcast Diffusion', 'Mixed Color Temperature',
    'Strip Lighting', 'Fluorescent Tube', 'LED Panel Soft', 'Kino Flo',
    'HMI Daylight', 'Carbon Arc Light', 'Firelight Flicker', 'Neon Tube Sign',
    'Lava Lamp Glow', 'Strobe / Flash Burst', 'Twilight Gradient', 'Half-Frost Diffusion',
    'Cookie / Cucoloris Pattern', 'Rag Diffusion', 'Ultra-Soft Sky Panel',
    'Cross-Backlight', 'Kicker Light', 'Eye Light Catchlight', 'Lens Flare Source',
    'Edge Ribbon Light', 'Top Hair Light', 'Background Accent Wash'
];

export const PHOTOGRAPHY_STYLES = [
    'Street Photography',
    'Portrait Photography',
    'Landscape Photography',
    'Wildlife Photography',
    'Macro Photography',
    'Architectural Photography',
    'Fashion Photography',
    'Food Photography',
    'Abstract Photography',
    'Documentary Photography',
    'Glamour Photography',
    'Still Life Photography',
    'Astro Photography',
    'Underwater Photography',
    'Sports Action Photography',
    'Concert Photography',
    'Editorial Photography',
    'Product Photography',
    'Real Estate Photography',
    'Urbex Photography',
    'Drone / Aerial Photography',
    'Photojournalism',
    'Fine Art Photography',
    'Boudoir Photography',
    'Night Street Photography',
    'Seascape Long Exposure',
    'Birding Photography',
    'Scientific / Micro Photography',
    'Pet Photography',
    'Wedding Photography',
    'Event Photography',
    'Travel Photography'
];

export const CAMERA_TYPES = [
    'Cinema Camera',
    'Mirrorless Camera',
    'Medium Format Camera',
    'DSLR',
    'Analog Film Camera',
    'Rangefinder Camera',
    'Action Camera',
    'Drone / Aerial Camera',
    'Smartphone Camera'
];

export const CAMERA_MODELS_BY_TYPE: Record<string, string[]> = {
    'Cinema Camera': [
        'ARRI Alexa 35',
        'ARRI Alexa Mini LF',
        'ARRI Alexa 65',
        'RED V-RAPTOR XL',
        'RED KOMODO-X',
        'Sony Venice 2',
        'Sony FX9',
        'Sony FX6',
        'Blackmagic URSA Mini Pro 12K',
        'Panavision Millennium DXL2',
        'Canon EOS C500 Mark II',
        'Sony BURANO'
    ],
    'Mirrorless Camera': [
        'Sony A7R V',
        'Sony A1',
        'Sony A7S III',
        'Canon EOS R3',
        'Canon EOS R5 Mark II',
        'Nikon Z9',
        'Nikon Z8',
        'Fujifilm X-H2S',
        'Fujifilm X-T5',
        'Panasonic Lumix S1H',
        'Leica SL3',
        'Nikon Z6 III'
    ],
    'Medium Format Camera': [
        'Fujifilm GFX 100 II',
        'Fujifilm GFX 100S II',
        'Hasselblad X2D 100C',
        'Hasselblad H6D-100c',
        'Phase One XF IQ4',
        'Leica S3',
        'Fujifilm GFX100RF'
    ],
    'DSLR': [
        'Canon EOS-1D X Mark III',
        'Canon EOS 5D Mark IV',
        'Nikon D6',
        'Nikon D850',
        'Canon EOS R1'
    ],
    'Analog Film Camera': [
        'Hasselblad 500C/M',
        'Leica M6',
        'Contax T2',
        'Mamiya RZ67',
        'Pentax 67',
        'Nikon F6',
        'Pentax 17',
        'Leica M6 Reissue'
    ],
    'Rangefinder Camera': [
        'Leica M11',
        'Leica M11-P',
        'Leica M10-R',
        'Fujifilm X-Pro3'
    ],
    'Action Camera': [
        'GoPro Hero 13 Black',
        'DJI Osmo Action 5 Pro',
        'Insta360 X4',
        'Insta360 Ace Pro 2'
    ],
    'Drone / Aerial Camera': [
        'DJI Mavic 4 Pro',
        'DJI Air 3S',
        'DJI Mini 4 Pro',
        'DJI Inspire 3',
        'Freefly Alta X'
    ],
    'Smartphone Camera': [
        'iPhone 17 Pro Max',
        'Samsung Galaxy S25 Ultra',
        'Google Pixel 10 Pro',
        'Xiaomi 15 Ultra'
    ]
};

export const ALL_PROFESSIONAL_CAMERA_MODELS = Object.values(CAMERA_MODELS_BY_TYPE).flat();

export const CAMERA_MOVEMENT_OPTIONS: DescriptiveOption[] = [
    { name: 'Static Camera', description: 'Fixed position with no movement.' },
    { name: 'Dolly', description: 'Camera moves toward or away from the subject on a track.' },
    { name: 'Slow Dolly In', description: 'Gradual movement towards the subject for tension.' },
    { name: 'Slow Dolly Out', description: 'Gradual movement away to reveal environment.' },
    { name: 'Fast Dolly In', description: 'Rapid movement towards the subject for impact.' },
    { name: 'Vertigo Effect', description: 'Simultaneous dolly-in and zoom-out (Dolly Zoom).' },
    { name: 'Extreme Macro Zoom', description: 'Ultra-tight focus shifting to reveal micro-details.' },
    { name: 'Cosmic Hyper Zoom', description: 'Seamless zoom from planetary scale to molecular detail.' },
    { name: 'Panning Shot', description: 'Camera pivots horizontally from a fixed point.' },
    { name: 'Tilting Shot', description: 'Camera pivots vertically (up or down).' },
    { name: 'Tilt Up', description: 'Camera pivots upward to reveal height.' },
    { name: 'Tilt Down', description: 'Camera pivots downward to reveal the ground.' },
    { name: 'Camera Truck Left', description: 'Camera moves physically left on a parallel plane.' },
    { name: 'Camera Truck Right', description: 'Camera moves physically right on a parallel plane.' },
    { name: 'Lateral Truck Left', description: 'Horizontal sideway movement at constant height.' },
    { name: 'Lateral Truck Right', description: 'Horizontal sideway movement at constant height.' },
    { name: 'Orbit 360', description: 'Camera circles the subject in a full rotation.' },
    { name: 'Fast 360 Orbit', description: 'High-speed circular rotation for energy.' },
    { name: 'Slow Cinematic Arc', description: 'Graceful partial circular movement for drama.' },
    { name: 'Pedestal Up', description: 'Moving the entire camera vertically up.' },
    { name: 'Pedestal Down', description: 'Moving the entire camera vertically down.' },
    { name: 'Crane Up', description: 'Elevating camera on a mechanical arm for scale.' },
    { name: 'Crane Down', description: 'Lowering camera on a mechanical arm.' },
    { name: 'Smooth Optical Zoom In', description: 'Lens magnification increasing focal length.' },
    { name: 'Smooth Optical Zoom Out', description: 'Lens magnification decreasing focal length.' },
    { name: 'Snap Zoom', description: 'Instant, aggressive focal length jump.' },
    { name: 'Rack Focus', description: 'Shifting focus between foreground and background.' },
    { name: 'Dolly Zoom', description: 'Distorting perspective while keeping subject size constant.' },
    { name: 'Tracking Shot', description: 'Camera follows subject movement at constant distance.' },
    { name: 'Leading Shot', description: 'Camera moves backward while facing a following subject.' },
    { name: 'Following Shot', description: 'Camera moves forward while following a subject.' },
    { name: 'Parallel Shot', description: 'Camera tracks alongside the subject laterally.' },
    { name: 'POV Walk', description: 'First-person perspective walking motion.' },
    { name: 'Handheld Movement', description: 'Natural, slightly shaky manual operation.' },
    { name: 'Handheld Documentary Style', description: 'Gritty, reactive, and kinetic manual camera.' },
    { name: 'Whip Pan', description: 'Extremely fast horizontal pivot causing motion blur.' },
    { name: 'Dutch Angle', description: 'Tilted horizon for psychological instability.' },
    { name: 'Drone Flyover', description: 'Aerial movement passing over a landscape.' },
    { name: 'Epic Drone Reveal', description: 'Starting low/hidden and rising to reveal a vista.' },
    { name: 'Large Scale Drone Orbit', description: 'Aerial circle around a landmark or terrain.' },
    { name: 'FPV Drone Aggressive', description: 'High-speed, acrobatic aerial maneuvers.' },
    { name: 'Top Down', description: 'Birds-eye view looking directly perpendicular to ground.' },
    { name: 'Worms Eye Tracking', description: 'Following movement from a ground-level perspective.' },
    { name: 'Snorricam Shot', description: 'Camera rigged to the actor for a locked-face POV.' },
    { name: 'Robot-Arm Hyperspeed (Bolt Cam)', description: 'Programmable high-speed robotic arm moves.' },
    { name: 'Cable Cam Flythrough', description: 'Suspended camera on cables soaring through a scene.' },
    { name: 'Gimbal Low-Mode Run', description: 'Low-to-ground gimbal walk for dynamic tracking.' },
    { name: 'Periscope Probe Move', description: 'Low-angle probe lens tracking parallel to ground.' },
    { name: 'Roll-Locked FPV Dive', description: 'FPV drone maintaining level horizon while diving.' },
    { name: 'Step-Printed Handheld', description: 'Handheld with staccato frame-doubled motion.' },
    { name: 'Slider Close-Up', description: 'Precise short-distance slider movement for detail.' },
    { name: 'Pan Right', description: 'Smooth horizontal pivot from left to right, ending on a clear composition.' },
    { name: 'Pan Left', description: 'Smooth horizontal pivot from right to left, ending on a clear composition.' },
    { name: 'Whip Pan Right', description: 'Rapid rightward pivot with brief motion blur that settles on a new target.' },
    { name: 'Whip Pan Left', description: 'Rapid leftward pivot with brief motion blur that settles on a new target.' },
    { name: 'Fast Zoom In', description: 'Quick, decisive optical zoom toward the main subject.' },
    { name: 'Fast Zoom Out', description: 'Quick, decisive optical zoom that opens up the surrounding scene.' },
    { name: 'Crash Zoom In', description: 'Punchy, ultra-fast zoom into a readable focal point.' },
    { name: 'Crash Zoom Out', description: 'Punchy, ultra-fast zoom away to reveal the wider setting.' },
    { name: 'Dolly Out', description: 'Controlled physical pull-back that reveals more of the environment.' },
    { name: 'Fast Dolly Out', description: 'Rapid physical pull-back for an abrupt reveal or impact.' },
    { name: 'Slider Right', description: 'Short, controlled slide right that creates foreground-to-background parallax.' },
    { name: 'Slider Left', description: 'Short, controlled slide left that creates foreground-to-background parallax.' },
    { name: 'Push Past / Pass-By', description: 'Forward glide past a near foreground object into the space beyond.' },
    { name: 'Arc Right', description: 'Measured curved move around the subject toward its right side.' },
    { name: 'Arc Left', description: 'Measured curved move around the subject toward its left side.' },
    { name: 'Orbit Clockwise', description: 'Smooth clockwise circle around a centered subject at a consistent radius.' },
    { name: 'Orbit Counterclockwise', description: 'Smooth counterclockwise circle around a centered subject at a consistent radius.' },
    { name: 'Follow Shot (Over-the-Shoulder)', description: 'Track behind the subject at shoulder height, keeping their route visible ahead.' },
    { name: 'Reverse Tracking Shot', description: 'Move backward ahead of a walking subject while maintaining front-facing framing.' },
    { name: 'Low Tracking Shot', description: 'Track alongside the action from ground or below-waist height.' },
    { name: 'Vehicle Tracking Shot', description: 'Match a vehicle’s pace while holding it stable against a moving environment.' },
    { name: 'Chase Shot', description: 'Fast, reactive follow move that stays close to a moving subject.' },
    { name: 'Drone Push In', description: 'Controlled aerial glide forward toward a subject or destination.' },
    { name: 'Drone Pull Back', description: 'Controlled aerial retreat that progressively reveals the landscape.' },
    { name: 'Helicopter-Style Aerial', description: 'Broad, high-altitude flight path with stable large-scale framing.' },
    { name: 'First-Person View', description: 'Human eye-height forward movement from the character’s perspective.' },
    { name: 'Infinite Zoom', description: 'Continuous centered zoom inward, accelerating into the next visual world.' },
    { name: 'Earth Zoom Out', description: 'Rapid pull from a local point outward through city, landscape, and planet scale.' },
    { name: 'Pass-Through Movement', description: 'Centered glide through a visible surface, barrier, or opening into a new space.' }
];

export const MOTION_OPTIONS: DescriptiveOption[] = [
    { name: 'Subtle Movement', description: 'Micro-motions and gentle idling.' },
    { name: 'Reveal from Behind', description: 'Wipe movement uncovering a hidden subject.' },
    { name: 'Through Shot', description: 'Flying through an aperture or narrow opening.' },
    { name: 'Reveal from Blur', description: 'Fade in from a defocused or soft state.' },
    { name: 'Fast Action', description: 'High-velocity kinetic energy.' },
    { name: 'Fluid Motion', description: 'Smooth, liquid-like transitions.' },
    { name: 'Slow Motion', description: 'Temporal dilation for detail preservation.' },
    { name: 'Explosive Energy', description: 'Burst of speed and particle displacement.' },
    { name: 'Hyperlapse', description: 'Moving time-lapse with camera displacement.' },
    { name: 'Bullet Time', description: 'Frozen moment with rotating camera view.' },
    { name: 'Barrel Roll', description: 'Full 360-degree rotation on the Z-axis.' },
    { name: 'Graceful Flow', description: 'Elegant, rhythmic pacing.' },
    { name: 'Chaotic Motion', description: 'Unpredictable and high-turbulence physics.' },
    { name: 'Time-lapse Style', description: 'Rapid progression of environmental changes.' },
    { name: 'Windy Atmosphere', description: 'Physical response to high-velocity air.' },
    { name: 'High-Speed Chase', description: 'Intense, focused directional velocity.' },
    { name: 'Jittery Shaking', description: 'High-frequency vibration and instability.' },
    { name: 'Elastic Bounce', description: 'Physics with recoil and squash/stretch.' },
    { name: 'Swirling Vortex', description: 'Centripetal rotation around a core.' },
    { name: 'Temporal Warp', description: 'Distortion of time and spatial consistency.' },
    { name: 'Liquid Ripple', description: 'Wave propagation across surfaces.' },
    { name: 'Parkour Flow', description: 'Fluid traversal with dynamic jumps and vaults.' },
    { name: 'Cloth Simulation Billow', description: 'Fabric physics with wind and drag.' },
    { name: 'Hair in Wind', description: 'Strand-based hair reacting to directional flow.' },
    { name: 'Particle Disintegration', description: 'Breaking apart into many small fragments.' },
    { name: 'Growth Time-Lapse', description: 'Organic expansion from seed to full form.' },
    { name: 'Ferrofluid Morph', description: 'Liquid metal shaping into spike formations.' },
    { name: 'Murmuration Swarm', description: 'Collective flocking behavior with fluid paths.' },
    { name: 'Shatter / Break', description: 'Brittle fracture into debris.' }
];

export const LENS_TYPES = [
    'Wide-Angle Lens', 'Telephoto Lens', 'Macro Lens', 'Prime Lens (50mm)', 'Fisheye Lens',
    'Tilt-Shift Lens', 'Anamorphic Lens', 'Lens Flare',
    '24mm Environmental Lens', '35mm Documentary Lens', '85mm f/1.2 Portrait Lens',
    '135mm Compression Lens', '600mm Super-Telephoto', 'Probe Lens',
    'Pinhole Lens', 'MP-E Ultra-Macro', 'Cine Prime Set',
    'Vintage Uncoated Glass', 'Mirror / Catadioptric Lens', 'Zoom Lens (Variable Focal)',
    'Super-Wide 14mm', '400mm Sports Lens'
];

export const ANALOG_FILM_STOCKS = [
    'Kodak Portra 160', 'Kodak Portra 400', 'Kodak Ektar 100', 'Kodak Gold 200', 'Kodak Tri-X 400',
    'Fujifilm Velvia 50', 'Fujifilm Provia 100F', 'Fujifilm Superia 400', 'CineStill 800T',
    'Ilford HP5 Plus 400', 'Lomography Color Negative 400', 'Polaroid 600', 'Agfa Vista 400',
    'Kodak Portra 800', 'Kodak Ektachrome E100', 'Fujifilm Pro 400H',
    'Kodak Vision3 500T', 'Kodak Vision3 250D', 'Kodak Aerochrome IR',
    'Fomapan 100', 'Kentmere 400', 'Ilford Delta 3200',
    'Fujifilm Acros II', 'Kodak Ultramax 400', 'Lomography Lomochrome Metropolis',
    'Ilford XP2 Super 400'
];

export const FACIAL_EXPRESSIONS = [
    'Neutral / Calm',
    'Joyful / Laughing',
    'Slight Smile',
    'Smirking / Playful',
    'Surprised / Shocked',
    'Angry / Furious',
    'Sad / Tearful',
    'Fearful / Terrified',
    'Disgusted',
    'Contemptuous',
    'Pensive / Thoughtful',
    'Determined / Intense',
    'Confused / Puzzled',
    'Bored / Disinterested',
    'Sleepy / Yawning',
    'Seductive / Sultry',
    'Winking',
    'Screaming',
    'Grinning',
    'Stoic / Expressionless',
    'Awestruck',
    'Smug',
    'Gritted Teeth',
    'Tearful Smile',
    'Thousand-Yard Stare',
    'Mid-Laugh Candid',
    'Eyes Closed Serene',
    'Biting Lip'
];

export const HAIR_STYLES = [
    'Buzz Cut',
    'Pixie Cut',
    'Bob Cut',
    'Shoulder Length',
    'Long Flowing Hair',
    'Braided / Cornrows',
    'Dreadlocks',
    'Afro',
    'Mohawk',
    'Undercut',
    'Messy / Bedhead',
    'Slicked Back',
    'Ponytail',
    'Pigtails',
    'Bun / Top Knot',
    'Bald / Shaved',
    'Wavy',
    'Curly',
    'Straight',
    'Frizzy',
    'Wolf Cut',
    'Mullet',
    'Shag',
    'Butterfly Cut',
    'Curtain Bangs',
    'Box Braids',
    'Space Buns',
    'Finger Waves',
    'French Bob',
    'Jellyfish Cut',
    'Taper Fade',
    'Twists',
    'Bantu Knots',
    'Asymmetrical Bob'
];

export const EYE_COLORS = [
    'Blue',
    'Brown',
    'Green',
    'Hazel',
    'Amber',
    'Gray',
    'Violet',
    'Heterochromia (Two-toned)',
    'Glowing / Luminous',
    'Piercing Light Blue',
    'Deep Dark Brown',
    'Sectoral Heterochromia',
    'Red Albino',
    'Black Sclera (Fantasy)'
];

export const SKIN_TEXTURES = [
    'Smooth / Flawless',
    'Freckled',
    'Weathered / Wrinkled',
    'Pores / Realistic Texture',
    'Visible Pores',
    'Micro-Pores',
    'Peach Fuzz / Vellus Hair',
    'Tanned',
    'Pale / Porcelain',
    'Scarred',
    'Tattooed',
    'Sweaty / Glistening',
    'Dirty / Gritty',
    'Vitiligo Patterns',
    'Sunburst Freckles',
    'Rosacea / Redness',
    'Oily / Shiny',
    'Matte Finish',
    'Pockmarks',
    'Acne / Blemishes',
    'Subsurface Scattering / Translucent',
    'Micro-Pigmentation',
    'Veins Visible',
    'Age Spots / Liver Spots',
    'Birthmarks',
    'Stretch Marks',
    'Cellulite',
    'Goosebumps',
    'Melasma',
    'Dermal Piercings',
    'Henna Patterns',
    'Metallic Body Paint',
    'Cracked Porcelain (Stylized)',
    'Dry / Flaking'
];

export const REALISM_OPTIONS = [
    'Hyper-Realistic',
    'Photorealistic',
    'Ultra-Detailed',
    'Unreal Engine 5 Render',
    'Unreal Engine 5.4 Lumen Path Tracing',
    'Octane Render',
    'Octane Spectral Renderer',
    'Brutalism / Raw Concrete Aesthetic',
    'Atmos / Atmospheric Perspective',
    'Raw Photo',
    'Candid Photography',
    'Unedited',
    'Documentary Style',
    'Polaroid',
    'Amateur Photography',
    'Cinematic Realism',
    'Scientific Photography',
    'Micro-detailed',
    'Imperfection / Flawed Realism',
    'Life-like',
    'Natural Lighting',
    'Unfiltered',
    'Smartphone Snapshot Realism',
    'Editorial Retouch',
    'Medium-Format Digital Clarity',
    'Film Scan Realism'
];

export const CLOTHING_STYLES = [
    'Casual / T-shirt & Jeans',
    'Formal / Suit & Tie',
    'Business Casual',
    'Streetwear / Techwear',
    'Cyberpunk / Futuristic',
    'Victorian / Period Dress',
    'Medieval / Fantasy Armor',
    'Athletic / Gym Wear',
    'Bohemian / Hippie',
    'Minimalist / Monochromatic',
    'High-Fashion / Avant-Garde',
    'Traditional / Cultural Garb',
    'Tactical / Military Gear',
    'Summer / Beachwear',
    'Winter / Heavy Coat',
    'Y2K Revival',
    'Gorpcore Shell Layers',
    'Dark Academia Knitwear',
    'Quiet Luxury Tailoring',
    'K-Fashion Street',
    'Cyber-Goth',
    'Western / Cowboycore',
    'Regencycore',
    'Balletcore',
    'Utility Workwear',
    'Festival Wear',
    'Haute Couture Gown',
    'Preppy / Ivy League',
    'Rave / Festival Gear',
    'Mori Kei (Forest Style)'
];

export const VIDEO_EFFECTS = [
    'Time-lapse',
    'Hyper-lapse',
    'Slow Motion (Slo-mo)',
    'Fast Motion',
    'Reverse Motion',
    'Glitch Effect',
    'VHS Style',
    'Cinematic Grain',
    'Color Grading',
    'Light Leaks',
    'Double Exposure',
    'Bokeh Bloom',
    'Anamorphic Streak',
    'Motion Blur',
    'Freeze Frame',
    'Ken Burns Effect',
    'Speed Ramp',
    'Crash Zoom Punch-In',
    'Match-Cut Morph',
    'Seamless Loop',
    'Datamosh',
    'Projector Flicker',
    'Day-for-Night Grade',
    'Split Diopter',
    'Jump Cut',
    'GoPro Wide Distortion'
];

export const MUSIC_GENRES = [
    'Synthwave', 'Phonk', 'Hyperpop', 'Drum & Bass', 'Lo-fi Hip Hop',
    'Afrobeats', 'Amapiano', 'City Pop', 'Shoegaze', 'Post-Rock',
    'Neo-Soul', 'UK Drill', 'Reggaeton', 'Cumbia', 'Bossa Nova',
    'Metalcore', 'Djent', 'Dark Ambient', 'Epic Trailer Orchestral',
    'Chiptune', 'Jersey Club', 'Breakcore', 'Gospel', 'Bluegrass',
    'House (Deep)', 'Techno (Minimal)', 'Trance (Progressive)', 'Dubstep (Melodic)',
    'Jazz (Contemporary)', 'Funk (P-Funk)', 'R&B (Alternative)', 'Hip Hop (Boom Bap)',
    'Country (Outlaw)', 'Folk (Indie)', 'Soul (Philly)', 'Disco (Nu-Disco)',
    'Ambient (Drone)', 'IDM (Glitch)', 'Footwork', 'Jungle',
    'Garage (UK)', 'Grime', 'Trap (Southern)', 'Drill (Chicago)',
    'Reggae (Roots)', 'Dub (Instrumental)', 'Ska (2-Tone)', 'Punk (Hardcore)',
    'Emo (Midwest)', 'Math Rock', 'Prog Rock', 'Krautrock',
    'Samba', 'Tango (Electro)', 'Flamenco (Nuevo)', 'K-Pop (4th Gen)',
    'J-Pop (Shibuya-kei)', 'Mande (West African)', 'Bollywood (Film Music)',
    'Classical (Minimalist)', 'Opera (Modern)', 'Musical Theatre'
];

export const INSTRUMENTATION = [
    'Analog Synth Pads', '808 Sub-Bass', 'Live Brass Section', 'String Quartet',
    'Nylon Guitar', 'Upright Bass', 'Modular Sequences', 'Taiko Drums',
    'Hang Drum', 'Mellotron', 'Theremin', 'Gamelan',
    'Fender Rhodes', 'Hammond Organ', 'Moog Bass', 'ARP 2600 Arpeggio',
    'Acoustic Drum Kit (Vintage)', 'Electronic Drum Machine (808)', 'Tambourine Shake',
    'Steel Pan', 'Sitar', 'Shakuhachi Flute', 'Bagpipes',
    'Pedal Steel Guitar', 'Wah-Wah Guitar', 'Slide Guitar', '12-String Acoustic',
    'Saw Wave Lead', 'Sine Wave Sub', 'FM Synth Bell', 'Granular Texture',
    'Orchestral Swells', 'Pizzicato Strings', 'French Horn', 'Piccolo Trumpet',
    'Vibraphone', 'Marimba', 'Glockenspiel', 'Tubular Bells',
    'Didgeridoo', 'Koto', 'Erhu', 'Oud'
];

export const VOCAL_STYLES = [
    'Breathy Female Pop', 'Gritty Blues Baritone', 'Stacked Choir Harmonies',
    'Rapid Rap Flow', 'Falsetto Hook', 'Operatic Soprano',
    'Whisper-Sung', 'Vocoder / Talkbox', 'Autotuned Melodic',
    'Spoken Word', 'Throat Singing', 'Growl (Death Metal)',
    'Crooner (Sinatra Style)', 'Yodel', 'Scat Jazz',
    'Soul Belt', 'Head Voice (Falsetto)', 'Chest Voice (Power Belt)',
    'Harmonic Overtone Singing', 'Beatbox Percussion', 'Lullaby Soft',
    'Preaching Cadence', 'Rapping (Lyrical)', 'Rapping (Mumble)',
    'Call and Response Lead'
];

export const MUSIC_PRODUCTION_ERAS = [
    '60s Motown Mono', '70s Analog Funk', '80s Gated-Reverb Synth-Pop',
    '90s Boom Bap', 'Y2K Maximalist Pop', '2010s EDM Festival',
    'Modern Trap Hi-Fi', 'Lo-fi Cassette', 'Audiophile Binaural',
    'Doo-wop Mono', 'Surf Reverb Spring', 'Psychedelic Panning',
    'Disco Four-on-the-Floor', 'New Wave Gate', 'Grunge Wall of Distortion',
    'Trip Hop Dusty Vinyl', 'Nu-Metal Digital Clip', 'Blog House Lo-fi',
    'Hyperpop Glitch Compressed', 'Bedroom Pop Intimate'
];

export const TIME_OF_DAY = [
    'Pre-Dawn Blue', 'Sunrise', 'Harsh Noon', 'Golden Hour', 'Dusk',
    'Blue Hour', 'Neon Night', 'Overcast Midday', 'Midnight Moonlit',
    'Twilight Gradient', 'Late Afternoon Warm', 'Dawn Mist'
];

export const WEATHER_OPTIONS = [
    'Light Drizzle', 'Downpour', 'Fog Bank', 'Snowfall', 'Blizzard',
    'Heat Haze', 'Sandstorm', 'Lightning Storm', 'Rainbow After Rain',
    'Morning Mist', 'Hail', 'Overcast Grey', 'Partly Cloudy',
    'Sunny Clear', 'Heavy Humidity', 'Tornado Sky'
];

export const STYLING_TRENDS: DescriptiveOption[] = [
    { name: 'Poetcore', description: 'Literary Romance, Inky Neutrals, Soft Layers, Handwritten Details' },
    { name: 'Aliencore', description: 'Bionic Shapes, Iridescent Skin, Otherworldly Gloss, Acid Tones' },
    { name: 'Circuscore', description: 'Theatrical Stripes, Carnival Color, Playful Drama, Vintage Spectacle' },
    { name: '80s Maximalism', description: 'Power Shoulders, Lacquered Color, High Drama, Opulent Excess' },
    { name: 'Sportif', description: 'Technical Sportswear, Refined Tailoring, Performance Details, Clean Energy' },
    { name: 'Modern Heirloom', description: 'Vintage Craft, Rich Patina, Sentimental Objects, Collected Layers' },
    { name: 'Tactile Minimalism', description: 'Quiet Forms, Handmade Texture, Soft Neutrals, Material Warmth' },
    { name: 'Neo-Medieval', description: 'Heraldic Motifs, Chainmail Texture, Illuminated Color, Future Fantasy' },
    { name: 'Analog Craft Revival', description: 'Visible Paper Grain, Hand-Drawn Marks, Imperfect Print, Human Touch' },
    { name: 'Soft Industrial', description: 'Brushed Metal, Translucent Plastic, Rounded Utility, Gentle Light' },
    { name: 'Night Garden', description: 'Botanical Darkness, Wet Foliage, Jewel Tones, Nocturnal Romance' },
    { name: 'Desert Modern', description: 'Sun-Baked Earth Tones, Sculptural Forms, Sparse Luxury, Long Shadows' },
    { name: 'Hyperlocal Nostalgia', description: 'Everyday Landmarks, Community Ephemera, Familiar Texture, Memory Haze' },
    { name: 'Romantic Utility', description: 'Practical Shapes, Soft Fabrics, Feminine Detail, Everyday Elegance' },
    { name: 'Power Dressing Revival', description: 'Strong Shoulders, Precise Tailoring, Confident Proportion, Polished Authority' },
    { name: 'Refined Grunge', description: 'Washed Texture, Dark Layers, Distressed Detail, Deliberate Edge' },
    { name: 'Modern Bohemia', description: 'Relaxed Layers, Artisan Pattern, Sun-Faded Color, Free-Spirited Ease' },
    { name: 'Contemporary Preppy', description: 'Clean Knitwear, Collegiate Detail, Crisp Stripes, Relaxed Structure' },
    { name: 'Sculptural Tailoring', description: 'Architectural Volume, Precise Seams, Strong Silhouette, Gallery Polish' },
    { name: 'Eclectic Maximalism', description: 'Layered Pattern, Collected Color, Bold Accessories, Joyful Excess' },
    { name: 'Quiet Luxury', description: 'Fine Natural Fibers, Understated Palette, Timeless Cut, Discreet Quality' },
    { name: 'Retro Futurism', description: 'Optimistic Space Age, Chrome Curves, Vintage Tech, Saturated Color' }
];

export const COLOR_GRADES = [
    'Teal & Orange Blockbuster', 'Bleach Bypass', 'Day-for-Night',
    'Kodak 2383 Print Emulation', 'Pastel Wash', 'High-Key Commercial',
    'Desaturated Nordic', 'Sepia Archive', 'Cross-Processed',
    'Infrared False Color', 'Warm Golden Glow', 'Cold Blue Tint',
    'Green Toxic / Sickness', 'Magenta / Pink Dream', 'Amber Vintage',
    'LUT: Cinematic LUT', 'Technicolor Three-Strip', 'Black & White High Contrast',
    'Silver Retention (Bleach Bypass)', 'Fade in Film',
    'Kodak Vision3 500T Tungsten', 'Kodak Vision3 250D Daylight',
    'Kodak Portra Soft Pastel', 'Kodak Ektar Vivid Color',
    'Fujifilm Eterna Soft Cinema', 'Fujifilm Velvia Rich Landscape',
    'Agfa Warm Vintage', 'Polaroid Faded Instant', 'Super 8 Home Movie',
    '16mm Documentary Grain', 'ECN-2 Film Negative', 'Chrome Slide Film',
    'Cyan & Amber Contrast', 'Emerald & Gold', 'Purple & Teal Neon',
    'Neon Noir Night', 'Moonlit Steel Blue', 'Desert Dust Ochre',
    'Sun-Bleached Western', 'Rainy Urban Sodium Vapor', 'Gothic Crimson & Black',
    'Pastel Spring Bloom', 'Earthy Terracotta', 'Jewel Tone Luxury',
    'Monochrome Silver Gelatin', 'Noir Green Shadows', 'Clean Editorial Neutral',
    'Warm Skin Tone Commercial', 'Cool Minimalist Editorial', 'Soft Matte Contrast',
    'Rich Blacks & Warm Highlights', 'Lifted Shadows Film Fade', 'High-Contrast Chrome',
    'Muted Documentary Naturalism', 'Split-Tone Blue Shadows / Orange Highlights',
    'Selective Color Accent'
];
