/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Nunito", "Inter", "Plus Jakarta Sans", "sans-serif"],
        display: ["Nunito", "Inter", "Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      colors: {},
    },
  },
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    themes: [
      {
        dich: {
          primary: "#78ff00",
          secondary: "#ffffff",
          accent: "#00d1ff",
          neutral: "#1a1a1a",
          "base-100": "#000000",
          "base-200": "#0a0a0a",
          "base-300": "#1a1a1a",
          "base-content": "#ffffff",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        pipboy: {
          primary: "#1aff1a",
          secondary: "#003300",
          accent: "#1aff1a",
          neutral: "#051105",
          "base-100": "#051105",
          "base-200": "#020802",
          "base-300": "#0a1a0a",
          "base-content": "#1aff1a",
          info: "#1aff1a",
          success: "#1aff1a",
          warning: "#1aff1a",
          error: "#ff0000",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },

      {
        abyss: {
          primary: "#00ffa3",
          secondary: "#00d1ff",
          accent: "#f3a01c",
          neutral: "#1e293b",
          "base-100": "#020617",
          "base-200": "#0f172a",
          "base-300": "#1e293b",
          "base-content": "#ffffff",
          info: "#0ea5e9",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        futurismo: {
          primary: "#f27d26",
          secondary: "#00ffa3",
          accent: "#ffffff",
          neutral: "#1a1a1a",
          "base-100": "#050505",
          "base-200": "#0f0f0f",
          "base-300": "#1a1a1a",
          "base-content": "#e5e5e5",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        sanrita: {
          primary: "#006b4a",
          secondary: "#00d1ff",
          accent: "#f3a01c",
          neutral: "#f1f5f9",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          info: "#0ea5e9",
          success: "#22c55e",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        orange: {
          primary: "#e86830",
          secondary: "#c71f16",
          neutral: "#2a2a2a",
          "base-100": "#1a1a1a",
          "base-200": "#2a2a2a",
          "base-300": "#3a3a3a",
        },
      },
      {
        Vanguard: {
          primary: "#ffcc00",
          secondary: "#332200",
          accent: "#ffcc00",
          neutral: "#0d0a00",
          "base-100": "#0d0a00",
          "base-200": "#050400",
          "base-300": "#1a1400",
          "base-content": "#ffcc00",
          info: "#ffcc00",
          success: "#ffcc00",
          warning: "#ffcc00",
          error: "#ff3300",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        MindTurbulence: {
          primary: "#e60012",
          secondary: "#ffc400",
          accent: "#fcc800",
          neutral: "#2a1b4d",
          "base-100": "#1a103c",
          "base-200": "#251756",
          "base-300": "#342273",
          "base-content": "#f9f8fa",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
      },
      {
        synthwave: {
          primary: "#ff00ff",
          secondary: "#00dbff",
          accent: "#ffea00",
          neutral: "#191d24",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          info: "#00dbff",
          success: "#00ff9f",
          warning: "#ffea00",
          error: "#ff0055",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      {
        light: {
          primary: "#570df8",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        dark: {
          primary: "#661ae6",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        cupcake: {
          primary: "#65c3c8",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        bumblebee: {
          primary: "#e0a82e",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        emerald: {
          primary: "#66cc8a",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        corporate: {
          primary: "#4b6bfb",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        retro: {
          primary: "#ef9995",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        cyberpunk: {
          primary: "#ff7598",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        valentine: {
          primary: "#e96d7b",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        halloween: {
          primary: "#f28c18",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        garden: {
          primary: "#5c7f67",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        forest: {
          primary: "#1eb854",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        aqua: {
          primary: "#09ecaf",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        lofi: {
          primary: "#00f0ff",
          secondary: "#004d4d",
          accent: "#ff003c",
          neutral: "#001a1a",
          "base-100": "#001a1a",
          "base-200": "#000d0d",
          "base-300": "#003333",
          "base-content": "#00f0ff",
          info: "#00f0ff",
          success: "#029090",
          warning: "#fcee54",
          error: "#ff003c",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        pastel: {
          primary: "#d1c1d7",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        fantasy: {
          primary: "#6e0b70",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        wireframe: {
          primary: "#b8b8b8",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        black: {
          primary: "#ffffff",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        luxury: {
          primary: "#ffffff",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        dracula: {
          primary: "#ff79c6",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        cmyk: {
          primary: "#45aeef",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        autumn: {
          primary: "#8c0327",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        business: {
          primary: "#1c4e80",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        acid: {
          primary: "#ff00ff",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        lemonade: {
          primary: "#519903",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        night: {
          primary: "#38bdf8",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        coffee: {
          primary: "#db924b",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        winter: {
          primary: "#047aff",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        dim: {
          primary: "#9fb3d8",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        nord: {
          primary: "#81a1c1",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
      {
        sunset: {
          primary: "#ff7e5f",
          "base-100": "#0d0221",
          "base-200": "#1a043c",
          "base-300": "#21064d",
          "base-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
        },
      },
    ],
  },
};
