/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Nunito', 'Inter', 'Plus Jakarta Sans', 'sans-serif'],
        display: ['Nunito', 'Inter', 'Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
      }
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        dich: {
          "primary": "#78ff00",
          "secondary": "#ffffff",
          "accent": "#00d1ff",
          "neutral": "#1a1a1a",
          "base-100": "#000000",
          "base-200": "#0a0a0a",
          "base-300": "#1a1a1a",
          "base-content": "#ffffff",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        pipboy: {
          "primary": "#1aff1a",
          "secondary": "#003300",
          "accent": "#1aff1a",
          "neutral": "#051105",
          "base-100": "#051105",
          "base-200": "#020802",
          "base-300": "#0a1a0a",
          "base-content": "#1aff1a",
          "info": "#1aff1a",
          "success": "#1aff1a",
          "warning": "#1aff1a",
          "error": "#ff0000",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      
      {
        abyss: {
          "primary": "#00ffa3",
          "secondary": "#00d1ff",
          "accent": "#f3a01c",
          "neutral": "#1e293b",
          "base-100": "#020617",
          "base-200": "#0f172a",
          "base-300": "#1e293b",
          "base-content": "#ffffff",
          "info": "#0ea5e9",
          "success": "#22c55e",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        futurismo: {
          "primary": "#f27d26",
          "secondary": "#00ffa3",
          "accent": "#ffffff",
          "neutral": "#1a1a1a",
          "base-100": "#050505",
          "base-200": "#0f0f0f",
          "base-300": "#1a1a1a",
          "base-content": "#e5e5e5",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        sanrita: {
          "primary": "#006b4a",
          "secondary": "#00d1ff",
          "accent": "#f3a01c",
          "neutral": "#f1f5f9",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          "info": "#0ea5e9",
          "success": "#22c55e",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--rounded-tab": "0",
        },
      },
      {
        orange: {
          "primary": "#e86830",
          "secondary": "#c71f16",
          "neutral": "#2a2a2a",
          "base-100": "#1a1a1a",
          "base-200": "#2a2a2a",
          "base-300": "#3a3a3a",
        },
      },
      {
        MindTurbulence: {
          "primary": "#e60012",
          "secondary": "#ffc400",
          "accent": "#fcc800",
          "neutral": "#2a1b4d",
          "base-100": "#1a103c",
          "base-200": "#251756",
          "base-300": "#342273",
          "base-content": "#f9f8fa",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
}
