// ─── Kollektiv Image Editor — Thumbnail Cache ────────────────────────────────
// Per-layer 128×128 thumbnail cache, module-scoped (no React involvement).
// Thumbnails are regenerated by CanvasRenderer only when a layer is listed in
// EditorState.dirtyLayerIds — see CanvasRenderer.regenerateDirtyThumbnails.

import type { LayerTransform } from '../types';

const THUMB_SIZE = 128;
const _cache = new Map<string, ImageBitmap>();

/** Returns the cached thumbnail for a layer, or null if none has been generated yet. */
export function getThumbnail(layerId: string): ImageBitmap | null {
  return _cache.get(layerId) ?? null;
}

/** Regenerates the cached thumbnail for a layer from its current bitmap + transform. */
export async function regenerate(
  layerId: string,
  bitmap: ImageBitmap,
  transform: LayerTransform,
): Promise<void> {
  const oc = new OffscreenCanvas(THUMB_SIZE, THUMB_SIZE);
  const ctx = oc.getContext('2d')!;
  // Fit the layer bitmap into 128×128 preserving aspect ratio
  const scale = Math.min(THUMB_SIZE / transform.size.width, THUMB_SIZE / transform.size.height);
  const sw = transform.size.width * scale;
  const sh = transform.size.height * scale;
  const ox = (THUMB_SIZE - sw) / 2;
  const oy = (THUMB_SIZE - sh) / 2;
  ctx.drawImage(bitmap, ox, oy, sw, sh);
  const newBitmap = await createImageBitmap(oc);
  // Close previous cached bitmap to free GPU memory
  _cache.get(layerId)?.close();
  _cache.set(layerId, newBitmap);
}

/** Drops and closes the cached thumbnail for a single layer (e.g. on layer removal). */
export function invalidate(layerId: string): void {
  _cache.get(layerId)?.close();
  _cache.delete(layerId);
}

/** Drops and closes every cached thumbnail. */
export function invalidateAll(): void {
  _cache.forEach(b => b.close());
  _cache.clear();
}

/** Called on editor unmount to release all GPU memory. */
export function dispose(): void {
  invalidateAll();
}
